package blivedm

const (
	CmdDanmaku           = "DANMU_MSG"
	CmdSysMsg            = "SYS_MSG"
	CmdSysGift           = "SYS_GIFT"
	CmdGuardMsg          = "GUARD_MSG"
	CmdSendGift          = "SEND_GIFT"
	CmdLive              = "LIVE"
	CmdPreparing         = "PREPARING"
	CmdEnd               = "END"
	CmdClose             = "CLOSE"
	CmdBlock             = "BLOCK"
	CmdRound             = "ROUND"
	CmdWelcome           = "WELCOME"
	CmdRefresh           = "REFRESH"
	CmdActivityRedPacket = "ACTIVITY_RED_PACKET"
	CmdAreaBlock         = "ROOM_LIMIT"
	CmdPkPre             = "PK_PRE"
	CmdPkEnd             = "PK_END"
	CmdPkSettle          = "PK_SETTLE"
	CmdPkMicEnd          = "PK_MIC_END"
	CmdHotRoomNotify     = "HOT_ROOM_NOTIFY"
	CmdPLAY_TAG          = "PLAY_TAG"
	CmdPLAY_PROGRESS_BAR = "PLAY_PROGRESS_BAR"
)

//
//"MATCH_TEAM_GIFT_RANK",
//"ACTIVITY_MATCH_GIFT",
//"ANIMATION",
//"CHANGE_ROOM_INFO",
//"COMBO_SEND",
//"CUT_OFF",
//"end",
//"DANMU_GIFT_LOTTERY_START",
//"DANMU_GIFT_LOTTERY_END",
//"DANMU_GIFT_LOTTERY_AWARD",
//"WARNING",
//"end",
//"DANMU_MSG",
//"USER_TOAST_MSG",
//"GUARD_ACHIEVEMENT_ROOM",
//"LIVE",
//"end",
//"MESSAGEBOX_USER_GAIN_MEDAL",
//"MESSAGEBOX_USER_MEDAL_CHANGE",
//"MESSAGEBOX_USER_MEDAL_COMPENSATION",
//"LITTLE_TIPS",
//"LITTLE_MESSAGE_BOX",
//"NOTICE_MSG",
//"PK_MATCH",
//"PK_PRE",
//"PK_START",
//"PK_PROCESS",
//"PK_END",
//"PK_SETTLE",
//"PK_AGAIN",
//"PK_MIC_END",
//"PK_BATTLE_PRE_NEW",
//"PK_BATTLE_START_NEW",
//"PK_BATTLE_PROCESS_NEW",
//"PK_BATTLE_PRO_TYPE",
//"PK_BATTLE_GIFT",
//"PK_BATTLE_SPECIAL_GIFT",
//"PK_BATTLE_CRIT",
//"PK_BATTLE_VOTES_ADD",
//"PK_BATTLE_END",
//"PK_BATTLE_SETTLE_V2",
//"PK_BATTLE_SETTLE_NEW",
//"PK_BATTLE_PUNISH_END",
//"PK_BATTLE_RANK_CHANGE",
//"PREPARING",
//"ROOM_REFRESH",
//"ROOM_SKIN_MSG",
//"TV_START",
//"RAFFLE_START",
//"TV_END",
//"RAFFLE_END",
//"PK_LOTTERY_START",
//"GUARD_LOTTERY_START",
//"ROOM_BLOCK_INTO",
//"ROOM_BLOCK_MSG",
//"ROOM_KICKOUT",
//"ROOM_LOCK",
//"ROOM_LIMIT",
//"ROOM_SILENT_ON",
//"end",
//"ROOM_SILENT_OFF",
//"end",
//"SEND_GIFT",
//"SEND_TOP",
//"SPECIAL_GIFT",
//"INTERACT_WORD",
//"ENTRY_EFFECT",
//"ENTRY_EFFECT_MUST_RECEIVE",
//"BOX_ACTIVITY_START",
//"end",
//"WIN_ACTIVITY",
//"WIN_ACTIVITY_USER",
//"ROOM_RANK",
//"HOUR_RANK_AWARDS",
//"end",
//"LOL_ACTIVITY",
//"ROOM_REAL_TIME_MESSAGE_UPDATE",
//"end",
//"VOICE_JOIN_STATUS",
//"ROOM_CHANGE",
//"end",
//"SUPER_CHAT_MESSAGE",
//"SUPER_CHAT_MESSAGE_DELETE",
//"SUPER_CHAT_ENTRANCE",
//"SUPER_CHAT_AUDIT",
//"ANCHOR_LOT_CHECKSTATUS",
//"ANCHOR_LOT_START",
//"ANCHOR_LOT_END",
//"ANCHOR_LOT_AWARD",
//"CHASE_FRAME_SWITCH",
//"WATCH_LPL_EXPIRED",
//"VIDEO_CONNECTION_JOIN_START",
//"VIDEO_CONNECTION_JOIN_END",
//"VIDEO_CONNECTION_MSG",
//"ROOM_BANNER",
//"WIDGET_BANNER",
//"ONLINE_RANK_V2",
//"ONLINE_RANK_TOP3",
//"HOT_RANK_CHANGED",
//"HOT_RANK_SETTLEMENT",
//"VTR_GIFT_LOTTERY",
//"COMMON_NOTICE_DANMAKU",
//"RED_POCKET_START",
//"end",
